source = colors.conf
$font = Campton Semibold

general {
  hide_cursor = false
}

animations {
  bezier = linear, 1, 1, 0, 0
  animation = fadeIn, 1, 5, linear
  animation = fadeOut, 1, 5, linear
}

background {
  path = screenshot
  blur_passes = 2
  blur_size = 8
  brightness = 0.6
}

input-field {
  monitor = DP-2

  inner_color = $surface
  font_color = $on_surface
  outer_color = $primary

  outline_thickness = 2
  placeholder_text = Input Password...
  font_family = $font

  size = 200, 40
  position = 0, 0
  valign = center
}

# clock
label {
  monitor = DP-2

  text = $TIME
  font_size = 96
  font_family = $font
  color = $on_surface

  valign = top
  position = 0, -100
}

# song title
label {
  monitor = DP-2

  text = cmd[update:100] playerctl metadata title
  font_family = $font
  font_size = 14
  color = $on_surface

  valign = bottom
  position = 32, 48
}

# song artist
label {
  monitor = DP-2

  text = cmd[update:100] playerctl metadata artist
  font_family = $font
  font_size = 10
  color = $on_surface

  valign = bottom
  position = 32, 28
}
